<?php

namespace App\Entity;

use App\Repository\ProfilPsychologiqueRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProfilPsychologiqueRepository::class)]
class ProfilPsychologique
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $scoreGlobal = null;

    #[ORM\Column(length: 100)]
    private ?string $profilType = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEvaluation = null;

    /**
     * AI-generated emotional insight / mindset advice (non-medical).
     * Generated by AiEmotionalInsightService from assessment (and later suivi data).
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $aiFeedback = null;

    #[ORM\OneToOne(targetEntity: Utilisateur::class, inversedBy: 'profilPsychologique')]
    #[ORM\JoinColumn(nullable: false, unique: true)]
    private ?Utilisateur $utilisateur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getScoreGlobal(): ?int
    {
        return $this->scoreGlobal;
    }

    public function setScoreGlobal(int $scoreGlobal): static
    {
        $this->scoreGlobal = $scoreGlobal;
        return $this;
    }

    public function getProfilType(): ?string
    {
        return $this->profilType;
    }

    public function setProfilType(string $profilType): static
    {
        $this->profilType = $profilType;
        return $this;
    }

    public function getDateEvaluation(): ?\DateTimeInterface
    {
        return $this->dateEvaluation;
    }

    public function setDateEvaluation(\DateTimeInterface $dateEvaluation): static
    {
        $this->dateEvaluation = $dateEvaluation;
        return $this;
    }

    public function getAiFeedback(): ?string
    {
        return $this->aiFeedback;
    }

    public function setAiFeedback(?string $aiFeedback): static
    {
        $this->aiFeedback = $aiFeedback;
        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): static
    {
        $this->utilisateur = $utilisateur;
        return $this;
    }
}
